---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Make sure sury.org repository can be used (Debian)
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - apt-transport-https

- name: Add apt reporitory key (Debian)
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
    keyring: /etc/apt/trusted.gpg.d/php.gpg

- name: Add DEB repository (Debian)
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
    update_cache: yes

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ item }}"
    state: "{{ php_packages_state }}"
    install_recommends: "{{ php_install_recommends }}"
  with_items: "{{ php_packages }}"
  register: php_package_install
  notify: restart webserver

- name: Delete OpCache configuration file if this role will provide one.
  file:
    path: "{{ item }}/{{ php_opcache_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: php_opcache_enable and php_package_install.changed
  notify: restart webserver
