---
- name: restart webserver
  service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
  notify: restart php-fpm
  when: php_enable_webserver

- name: restart php-fpm
  systemd:
    name: "{{ php_fpm_daemon }}"
    state: restarted
    daemon_reload: yes
  when: php_enable_php_fpm
